title: "찌니노트"
description: "이것저것 스터디 기록해두는 찌니의 노트"
permalink: post/:title
url: https://zininote.github.io
tag_order: [algorithm,dev]

markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        disable: true
